name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Format code
        run: npm run format

        ## check if any changes were made
      - name: Check for changes
        run: git diff --exit-code

        ## if changes were made, fail the build
      - name: Fail build if changes were made
        if: ${{ failure() }}
        run: exit 1 { echo "Code formatting required. Please run 'npm run format' and commit the changes."; }

        ## if no changes were made, continue with the build
      - name: Build project
        run: npm run build
